const Details = [
  {
    name: "Model 3",
    comment: "Order Online for",
    link: "Touchless Delivery",
    bgImage: "Images/model-3.jpg",
    leftBtn: "customer order",
    rightBtn: "existing inventory",
  },
  {
    name: "Model Y",
    comment: "Order Online for",
    link: "Touchless Delivery",
    bgImage: "Images/model-y.jpg",
    leftBtn: "customer order",
    rightBtn: "existing inventory",
  },
  {
    name: "Model S",
    comment: "Order Online for",
    link: "Touchless Delivery",
    bgImage: "Images/model-s.jpg",
    leftBtn: "customer order",
    rightBtn: "existing inventory",
  },
  {
    name: "Model X",
    comment: "Order Online for",
    link: "Touchless Delivery",
    bgImage: "Images/model-x.jpg",
    leftBtn: "customer order",
    rightBtn: "existing inventory",
  },
  {
    name: "Solar Panels",
    comment: "Lowest Cost Solar Panels in America",
    leftBtn: "Order Now",
    rightBtn: "Learn more",
    bgImage: "Images/solar-panel.jpg",
  },
  {
    name: "Solar Roof",
    comment: "Produce Clean Energy From Your Roof",
    leftBtn: "Order Now",
    rightBtn: "Learn more",
    bgImage: "Images/solar-roof.jpg",
  },
  {
    name: "Accessories",
    leftBtn: "Shop now",
    bgImage: "Images/accessories.jpg",
  },
];

const extraInfo = [
  "Model S",
  "Model 3",
  "Model X",
  "Model Y",
  "Solar Roof",
  "Solar Panels",
  "Existing Inventory",
  "Used Inventory",
  "Trade-In",
  "Test Drive",
  "Insurance",
  "Powerwall",
  "Commercial Energy",
  "Utilities",
  "Charging",
  "Find Us",
  "Support",
  "Investor Relations",
  "Shop",
  "Acount",
  "More",
];

export { Details, extraInfo };
